name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: read
jobs:
  Custom-Deploy-1:
    env:
      val: hoge
    outputs:
      msg: ${{ steps.execScript.outputs.msg }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 ${{ env.val }}"
      - uses: actions/checkout@v3
      - run:
          chmod +x ./scripts/${{ env.val }}.sh;
          echo "msg=$(./scripts/hoge.sh)" >> $GITHUB_OUTPUT
        shell: bash
        id: execScript

  Resolve:
    runs-on: ubuntu-latest
    needs:
      Custom-Deploy-1
    env:
      val: ${{ needs.Custom-Deploy-1.outputs.msg }}
    steps:
      - run: echo "🚅 ${{ env.val }}"
