name: GitHub Actions Demo
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
permissions:
  contents: read
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - run: echo "🔎 The name of your branch is ${{ github.ref }} and your repository is ${{ github.repository }}."
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."
      - run: echo "🖥️ The workflow is now ready to test your code on the runner."
      - name: List files in the repository
        run: |
          ls ${{ github.workspace }}
      - run: echo "🍏 This job's status is ${{ job.status }}."

  Custom-Deploy-1:
    env:
      val: hoge
    outputs:
      msg: ${{ steps.execScript.outputs.msg }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "🚀 $val"
      - uses: actions/checkout@v3
      - run: 
          chmod +x ./scripts/${{ env.val }}.sh;
          echo "msg=$(./scripts/hoge.sh)" >> $GITHUB_OUTPUT
        shell: bash
        id: execScript

  Resolve:
    runs-on: ubuntu-latest
    needs:
      Custom-Deploy-1
    env:
      val: needs.job1.outputs.msg
    steps:
      - run: echo ${{ env.msg }}
